---

# TODO: Is it really necessary to repeat this? Couldn't we just re-use the
# results of the first check combined with the results from the installation?
# Perhaps take the first list, then filter out those that successfully had
# python installed.
- name: Recheck python installation status
  raw: "test -e {{ lxd_containers_python_path }}"
  register: python_install_check
  failed_when: python_install_check['rc'] not in [0, 1]
  changed_when: false

- name: Tag systems with python installed for future task logic
  set_fact:
    python_installed: "{{ true if (python_install_check['rc'] == 0) else false | bool }}"

- name: DEBUG | Show results of setting fact
  debug:
    var: python_installed
    verbosity: "2"

# This task is performed if Python was found previously,
# regardless of whether a container was "bootstrapped" or not.
- name: CONTAINERS | Gather facts from containers with Python present
  setup:
    #gather_subset: network
  become: no
  # Any special meaning for this variable name?
  register: setup
  when: python_installed | default(false)

...
