---

# vim: ts=2:sw=2:et:ft=yaml
# -*- mode: yaml; indent-tabs-mode: nil; tab-width: 2 -*-
# code: language=yaml insertSpaces=true tabSize=2

# https://github.com/atc0005/ansible-playbook-lxd-testenv
# https://github.com/atc0005/ansible-role-lxd-testenv

- name: Install extra packages
  delegate_to: "{{ item }}"
  package:
    name: "{{ hostvars[item]['lxd_containers_packages_extra'] | default(lxd_containers_packages_extra) }}"
    state: present
  with_items:
    - "{{ groups['all'] }}"
  loop_control:
    label: >
      {{ item }} |
      Packages: {{ hostvars[item]['lxd_containers_packages_extra'] | default(lxd_containers_packages_extra) }}
  when: >
    hostvars[item]['python_installed'] | default(false)
    and
    (
      hostvars[item]['lxd_containers_packages_extra'] is defined
      and hostvars[item]['lxd_containers_packages_extra'] | length >0
      or hostvars[item]['lxd_containers_packages_extra'] is not defined
      and lxd_containers_packages_extra is defined
      and lxd_containers_packages_extra | length >0
    )
    and
    (
      hostvars[item]['lxd_containers_configure'] | default(false)
      or hostvars[item]['lxd_containers_configure'] is not defined
      and lxd_containers_configure | default(false)
    )

...
