---

# make sure all containers are running so that we can retrieve relevant
# info and then prune that info from the host (e.g., known_hosts, /etc/hosts)
- name: Ensure containers are running so we can pull required details
  delegate_to: localhost

  # The user may have opted to nuke containers on their own outside of
  # playbook control, so don't bomb out if a container is missing
  ignore_errors: yes

  lxd_container:
    name: "{{ inventory_hostname }}"
    state: started
    wait_for_ipv4_addresses: true
    timeout: 600
  when: lxd_host_remove_containers
  tags:
    - remove

...
