---

# vim: ts=2:sw=2:et:ft=yaml
# -*- mode: yaml; indent-tabs-mode: nil; tab-width: 2 -*-
# code: language=yaml insertSpaces=true tabSize=2

# https://github.com/atc0005/ansible-playbook-lxd-testenv
# https://github.com/atc0005/ansible-role-lxd-testenv

# Purpose: Install Docker related configuration in containers that may be used
# for Docker testing. A separate role is used to actually install Docker and
# related packages into those containers

- name: DOCKER | DEBUG | Display config file directory
  debug:
    msg: "{{ hostvars[item]['lxd_containers_docker_main_config_file'] | default(lxd_containers_docker_main_config_file) | dirname }}"
    verbosity: "2"
  with_items:
    - "{{ groups['all'] }}"
  loop_control:
    label: >
      {{ item }} |
      Config dir: {{ hostvars[item]['lxd_containers_docker_main_config_file'] | default(lxd_containers_docker_main_config_file) | dirname }}

- name: DOCKER | Create config file directory
  delegate_to: "{{ item }}"
  become: yes
  file:
    state: directory
    dest: "{{ hostvars[item]['lxd_containers_docker_main_config_file'] | default(lxd_containers_docker_main_config_file) | dirname }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ groups['all'] }}"
  loop_control:
    label: >
      {{ item }} |
      Config dir: {{ hostvars[item]['lxd_containers_docker_main_config_file'] | default(lxd_containers_docker_main_config_file) | dirname }}
  when: >
    hostvars[item]['python_installed'] | default(false)
    and
    (
      hostvars[item]['lxd_containers_docker_main_config_file'] is defined
      and hostvars[item]['lxd_containers_docker_main_config_file'] != ""
      or hostvars[item]['lxd_containers_docker_main_config_file'] is not defined
      and lxd_containers_docker_main_config_file is defined
      and lxd_containers_docker_main_config_file != ""
    )
    and
    (
      hostvars[item]['lxd_containers_configure'] | default(false)
      or hostvars[item]['lxd_containers_configure'] is not defined
      and lxd_containers_configure | default(false)
    )

- name: DOCKER | DEBUG | Display chosen storage driver
  debug:
    # Set via defaults/main.yml, already in scope for localhost
    var: hostvars[item]['lxd_containers_docker_storage_driver'] | default(lxd_containers_docker_storage_driver)
    verbosity: "1"
  with_items:
    - "{{ groups['all'] }}"
  loop_control:
    label: >
      {{ item }} |
      Storage driver: {{ hostvars[item]['lxd_containers_docker_storage_driver'] | default(lxd_containers_docker_storage_driver) }}

- name: DOCKER | Deploy base config file
  delegate_to: "{{ item }}"
  become: yes
  template:
    src: '{{ lxd_containers_docker_config_file_template }}'
    dest: "{{ hostvars[item]['lxd_containers_docker_main_config_file'] | default(lxd_containers_docker_main_config_file) }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ groups['all'] }}"
  loop_control:
    label: >
      {{ item }} |
      Config file: {{ hostvars[item]['lxd_containers_docker_main_config_file'] | default(lxd_containers_docker_main_config_file) }} |
      Storage driver: {{ hostvars[item]['lxd_containers_docker_storage_driver'] | default(lxd_containers_docker_storage_driver) }}
  when: >
    hostvars[item]['python_installed'] | default(false)
    and
    (
      hostvars[item]['lxd_containers_docker_main_config_file'] is defined
      and hostvars[item]['lxd_containers_docker_main_config_file'] != ""
      or hostvars[item]['lxd_containers_docker_main_config_file'] is not defined
      and lxd_containers_docker_main_config_file is defined
      and lxd_containers_docker_main_config_file != ""
    )
    and
    (
      hostvars[item]['lxd_containers_configure'] | default(false)
      or hostvars[item]['lxd_containers_configure'] is not defined
      and lxd_containers_configure | default(false)
    )

...
