---

# TODO: Is it really necessary to repeat this? Couldn't we just re-use the
# results of the first check combined with the results from the installation?
# Perhaps take the first list, then filter out those that successfully had
# python installed.
- name: Recheck python installation status
  delegate_to: "{{ item }}"
  delegate_facts: true
  raw: "test -e {{ hostvars[item]['lxd_containers_python_path'] | default(lxd_containers_python_path) }}"
  register: python_install_check
  failed_when: python_install_check['rc'] not in [0, 1]
  changed_when: false
  with_items:
    - "{{ groups['all'] }}"

- name: Tag systems with python installed for future task logic
  delegate_to: "{{ item['item'] }}"
  delegate_facts: true
  set_fact:
    python_installed: "{{ true if (item['rc'] == 0) else false | bool }}"
  with_items:
    - "{{ python_install_check['results'] }}"
  loop_control:
    label: >-
      {{ item['item'] }} |
      {{ 'Python available' if (item['rc'] == 0)
          else 'Python missing'
      }}

- name: DEBUG | Show results of setting fact
  debug:
    var: hostvars[item]['python_installed']
    verbosity: "2"
  with_items:
    - "{{ groups['all'] }}"

# This task is performed if Python was found previously,
# regardless of whether a container was "bootstrapped" or not.
- name: CONTAINERS | Gather facts from containers with Python present
  setup:
    #gather_subset: network
  become: no
  # Any special meaning for this variable name?
  register: setup
  delegate_to: "{{ item }}"
  delegate_facts: yes
  with_items:
    - "{{ groups['all'] }}"
  loop_control:
    label: >-
      {{ item }} |
      {{ 'Python available' if (hostvars[item]['python_installed'])
          else 'Python missing'
      }}
  when:
    - hostvars[item]['python_installed'] | default(false)

...
