---

# vim: ts=2:sw=2:et:ft=yaml
# -*- mode: yaml; indent-tabs-mode: nil; tab-width: 2 -*-
# code: language=yaml insertSpaces=true tabSize=2

# https://github.com/atc0005/ansible-playbook-lxd-testenv
# https://github.com/atc0005/ansible-role-lxd-testenv

- name: Install required packages
  package:
    name: "{{ lxd_containers_packages_required }}"
    state: present
  when:
    - python_installed | default(false)
    - lxd_containers_packages_required is defined
    - lxd_containers_packages_required | length >0
    - lxd_containers_configure | default(false)
  register: lxd_containers_packages_required_installation_results
  until: lxd_containers_packages_required_installation_results is success
  retries: "{{lxd_containers_package_installation_retry_attempts }}"
  delay: "{{ lxd_containers_package_installation_retry_delay }}"

...
