---

# vim: ts=2:sw=2:et:ft=yaml
# -*- mode: yaml; indent-tabs-mode: nil; tab-width: 2 -*-
# code: language=yaml insertSpaces=true tabSize=2

# https://github.com/atc0005/ansible-playbook-lxd-testenv
# https://github.com/atc0005/ansible-role-lxd-testenv

- name: Install extra packages
  package:
    name: "{{ lxd_containers_packages_extra }}"
    state: present
  when:
    - python_installed | default(false)
    - lxd_containers_packages_extra is defined
    - lxd_containers_packages_extra | length >0
    - lxd_containers_configure | default(false)

...
