---

# vim: ts=2:sw=2:et:ft=yaml
# -*- mode: yaml; indent-tabs-mode: nil; tab-width: 2 -*-
# code: language=yaml insertSpaces=true tabSize=2

# https://github.com/atc0005/ansible-playbook-lxd-testenv
# https://github.com/atc0005/ansible-role-lxd-testenv

# Purpose: Install Docker related configuration in containers that may be used
# for Docker testing. A separate role is used to actually install Docker and
# related packages into those containers

- name: DOCKER | DEBUG | Display config file directory
  debug:
    msg: "{{ lxd_containers_docker_main_config_file | dirname }}"
    verbosity: "2"

- name: DOCKER | Create config file directory
  become: yes
  file:
    state: directory
    dest: "{{ lxd_containers_docker_main_config_file | dirname }}"
    owner: root
    group: root
    mode: 0755
  when:
    - python_installed | default(false)
    - lxd_containers_docker_main_config_file is defined
    - lxd_containers_docker_main_config_file != ""
    - lxd_containers_configure | default(false)

- name: DOCKER | DEBUG | Display chosen storage driver
  debug:
    # Set via defaults/main.yml, already in scope for localhost
    var: lxd_containers_docker_storage_driver
    verbosity: "1"

- name: DOCKER | Deploy base config file
  become: yes
  template:
    src: '{{ lxd_containers_docker_config_file_template }}'
    dest: "{{ lxd_containers_docker_main_config_file }}"
    owner: root
    group: root
    mode: 0644
  when:
    - python_installed | default(false)
    - lxd_containers_docker_main_config_file is defined
    - lxd_containers_docker_main_config_file != ""
    - lxd_containers_configure | default(false)

...
