---

# vim: ts=2:sw=2:et:ft=yaml
# -*- mode: yaml; indent-tabs-mode: nil; tab-width: 2 -*-
# code: language=yaml insertSpaces=true tabSize=2

# https://github.com/atc0005/ansible-playbook-lxd-testenv
# https://github.com/atc0005/ansible-role-lxd-testenv

- name: Create LXD profile to enable Docker use in containers
  delegate_to: localhost

  # Attempt to limit runs to once per playbook run instead of for every node
  # that the playbook targets.
  run_once: true
  lxd_profile:
    name: docker
    state: present
    # * security.nesting is required for general Docker support
    # * overlay kernel module is needed for 'overlay' and 'overlay2' Docker
    #   storage driver support.
    config:
        "security.nesting": "true"
        "linux.kernel_modules": "overlay"
    description: Allow use of Docker in LXD containers

...
