---

# vim: ts=2:sw=2:et:ft=yaml
# -*- mode: yaml; indent-tabs-mode: nil; tab-width: 2 -*-
# code: language=yaml insertSpaces=true tabSize=2

# https://github.com/atc0005/ansible-playbook-lxd-testenv
# https://github.com/atc0005/ansible-role-lxd-testenv

- name: Remove Docker LXD profile
  delegate_to: localhost

  # Attempt to limit runs to once per playbook run instead of for every node
  # that the playbook targets.
  run_once: true
  lxd_profile:
    name: docker
    state: absent

  # Should be overridden at the playbook level (or higher)
  when:
    - lxd_host_remove_profiles | default(false)


...
