---

# vim: ts=2:sw=2:et:ft=yaml
# -*- mode: yaml; indent-tabs-mode: nil; tab-width: 2 -*-
# code: language=yaml insertSpaces=true tabSize=2

# https://github.com/atc0005/ansible-playbook-lxd-testenv
# https://github.com/atc0005/ansible-role-lxd-testenv

# Generate /etc/hosts with Ansible
# https://gist.github.com/rothgar/8793800
- name: "HOST | Update {{ lxd_host_etc_hosts_file }}"
  delegate_to: localhost
  become: yes
  run_once: true
  blockinfile:
    dest: "{{ lxd_host_etc_hosts_file }}"
    marker: "# {mark} This part managed by Ansible"
    block: |
      {% for h in groups['all'] %}
      {% if hostvars[h].ansible_default_ipv4 is defined
          and hostvars[h].ansible_default_ipv4.address is defined %}
      {{ hostvars[h].ansible_default_ipv4.address }} {{ h }}
      {% endif %}
      {% endfor %}
  when:
    - lxd_host_update_etc_hosts_file | default(false)

- name: "HOST | Add container host keys to {{ lxd_host_ssh_system_known_hosts_file }}"
  delegate_to: localhost
  run_once: true
  become: yes
  blockinfile:
    create: yes
    dest: "{{ lxd_host_ssh_system_known_hosts_file }}"
    marker: "# {mark} This part managed by Ansible"
    block: |
      {% for h in groups['all'] if hostvars[h].ansible_ssh_host_key_rsa_public is defined %}
      {{ h }} ssh-rsa {{ hostvars[h]['ansible_ssh_host_key_rsa_public'] }}
      {% endfor %}

      {% for h in groups['all'] if hostvars[h].ansible_ssh_host_key_ecdsa_public is defined %}
      {{ h }} ecdsa-sha2-nistp256 {{ hostvars[h]['ansible_ssh_host_key_ecdsa_public'] }}
      {% endfor %}

      {% for h in groups['all'] if hostvars[h].ansible_ssh_host_key_ed25519_public is defined %}
      {{ h }} ssh-ed25519 {{ hostvars[h]['ansible_ssh_host_key_ed25519_public'] }}
      {% endfor %}
  when:
    - lxd_host_update_system_known_hosts_file | default(false)

- name: "HOST | Add container host keys to {{ lxd_host_ssh_user_known_hosts_file }}"
  delegate_to: localhost
  run_once: true
  become: no
  blockinfile:
    create: yes
    dest: "{{ lxd_host_ssh_user_known_hosts_file }}"
    marker: "# {mark} This part managed by Ansible"
    block: |
      {% for h in groups['all'] if hostvars[h].ansible_ssh_host_key_rsa_public is defined %}
      {{ h }} ssh-rsa {{ hostvars[h]['ansible_ssh_host_key_rsa_public'] }}
      {% endfor %}

      {% for h in groups['all'] if hostvars[h].ansible_ssh_host_key_ecdsa_public is defined %}
      {{ h }} ecdsa-sha2-nistp256 {{ hostvars[h]['ansible_ssh_host_key_ecdsa_public'] }}
      {% endfor %}

      {% for h in groups['all'] if hostvars[h].ansible_ssh_host_key_ed25519_public is defined %}
      {{ h }} ssh-ed25519 {{ hostvars[h]['ansible_ssh_host_key_ed25519_public'] }}
      {% endfor %}
  when:
    - lxd_host_update_user_known_hosts_file | default(false)

- name: "HOST | Add container host entries to {{ lxd_host_ssh_client_system_config_file }}"
  delegate_to: localhost
  run_once: true
  become: yes
  blockinfile:
    # Allow the file to be created if needed
    create: yes
    dest: "{{ lxd_host_ssh_client_system_config_file }}"
    marker: "# {mark} This part managed by Ansible"
    block: |
      # LXD test container entries
      {% for h in groups['all'] %}
      {% if hostvars[h].ansible_default_ipv4 is defined
          and hostvars[h].ansible_default_ipv4.address is defined %}
      Host {{ h }} {{ hostvars[h].ansible_default_ipv4.address }}
        StrictHostKeyChecking no
        UserKnownHostsFile=/dev/null
        #User root
        LogLevel ERROR
      {% endif %}
      {% endfor %}
  when:
    - lxd_host_update_ssh_client_system_config_file | default(false)

- name: "HOST | Add container host entries to {{ lxd_host_ssh_client_user_config_file }}"
  delegate_to: localhost
  run_once: true
  become: no
  blockinfile:
    # Allow the file to be created if needed
    create: yes
    dest: "{{ lxd_host_ssh_client_user_config_file }}"
    marker: "# {mark} This part managed by Ansible"
    block: |
      # LXD test container entries
      {% for h in groups['all'] %}
      {% if hostvars[h].ansible_default_ipv4 is defined
          and hostvars[h].ansible_default_ipv4.address is defined %}
      Host {{ h }} {{ hostvars[h].ansible_default_ipv4.address }}
        StrictHostKeyChecking no
        UserKnownHostsFile=/dev/null
        #User root
        LogLevel ERROR
      {% endif %}
      {% endfor %}
  when:
    - lxd_host_update_ssh_client_user_config_file | default(false)

...
