---

# vim: ts=2:sw=2:et:ft=yaml
# -*- mode: yaml; indent-tabs-mode: nil; tab-width: 2 -*-
# code: language=yaml insertSpaces=true tabSize=2

# https://github.com/atc0005/ansible-playbook-lxd-testenv
# https://github.com/atc0005/ansible-role-lxd-testenv

- name: Remove LXD container settings
  import_tasks: host-remove-container-settings.yml

- name: Remove LXD containers
  import_tasks: host-remove-containers.yml

- name: Remove LXD profiles
  import_tasks: host-remove-lxd-profiles.yml

...
