---

# vim: ts=2:sw=2:et:ft=ansible
# -*- mode: ansible; indent-tabs-mode: nil; tab-width: 2 -*-
# code: language=ansible insertSpaces=true tabSize=2

- name: Remove LXD container settings
  import_tasks: host-remove-container-settings.yml

- name: Remove LXD containers
  import_tasks: host-remove-containers.yml

...
